language: node_js
node_js:
- stable
script:
- npm run travis
deploy:
  provider: npm
  skip_cleanup: true
  email: code+tuyapinpm@maxisom.me
  api_key:
    secure: jUrsCz909PuPA8jHRoJOdnWVMxM8t90SxS6TZn2t2pKwt7i9r2+HI7KTzCyu1lkhAxs95W2AKWqZZNlpmStsP6jF8+QTVaF2RKjGiu9lZ4b6IvP2faCFf1eztBQp0WScpHVtDNjmiPVNI+leHx/mAF7bmluvaNQrAqr2SL+I/loVOmdNa2wf45x2A1VxRYT7bA2DZBsOQ3hN1UjV5LnBerCWdC/MDRgYPsh2c+Gm00ag/fPKjUWQBlJwBPYwX75YNk+Ux25rW3yWJK6FrUm6gkd4kXAJN4+yE8piMvOdP7qrAkWaGofV7Ac/TRPAa5Z4VMCPHXh7/KxfVx852W41r2BSXUbTyiikFpAcwsoZ+NvPesl3G8RhaI7cRAwkhueka60syeLlt7JKljqD8eQYBIV/gh0FCG71oiz1RymZcCGKZIhqeEWPtZpB1fwLKwi0NAM8KCpK8QyMWUX7gbFZSFrLpAEDAlf7dnGkpq3dbQFkPPpKMoHZgTbP5579JySFCPoqO3iI70cKrx5xFx8et7g4HeNbcCLxTSK+OJShKNBiYEfp2KiZJqExy7OP22ztoHNT+aEmy9JgR+UlgAYqpwM8oRORO0NzUCE4/pPlUmGLrnrWbXDqeFfq06q5H2Itz3rJRLGWawnvjgH1UkQjbFg4IJhU9yk5jE/JTG2UPWM=
  on:
    tags: true
    repo: TuyaAPI/driver
    branch: master
