language: node_js
node_js:
- stable
script:
- npm run travis
deploy:
  provider: npm
  email: "code+tuyapinpm@maxisom.me"
  skip_cleanup: true
  api_key:
    secure: QwrMrHQa6xeL8+xKkpiSC4HJp49iqgw8yGzONqJX7VveplmBm5yY6H+7gOF6YGAbWNOmv+DnHev268OgkIVKEbGqhjiwIoGAeGmit6mB4Ioj62FAvg23EJlo/K7TfzZ+8p3aX5lUoy0Q+l3pBtJnu1sY5G1xcBsrRbtUkYPC5t1NQI6FmkAYSMSk7pHMtYZTz800JED01kBGGvHGX4lEYs+pVqK+/1NfRx48L4qPVC6ZxNAy39p1RuJGNeFWcGh3I9VwQtXp48TaJFM2QqxrLv7T+SsmGlM7mQGKYxyUQbWA3+/wEs8YIBSP1T066ZuChnt2LkLnmuu7WG3GKi7E+wYFNX6t0ea3opDThGcwYIJoEfiZDgITrqV3KOwwDDqyEMa/sDBpCW+47hbi9W2M1S9FGpm1OgdpTKhXsNPCbABrJlRABzdjp9BxwcJG6Mky2adhkjnk9oYa3wMVflT6c+pyuI/DNVrKTT3J1xt+uPREJCS8wxDLfFmuZx5pWTVrQS85wMFKqwPAalgymDzKZ45B6TqgJJRj5rx1Wdr6DiKYb+BSm6PEwr7ljffwUseNVRQfSspd3WZlzTM6Vhtoz9L70VFmxbeylIWu0ZqdhfFRyEGcNVZGYk+OcY+TGl3kXxkvt+XzYMk8jI1tB+3WOo+IwzXtDAZstY3Sgj8xqBU=
  on:
    tags: true
    repo: TuyaAPI/driver
    branch: master
