language: node_js
node_js:
- stable
script:
- npm run travis
deploy:
  provider: npm
  skip_cleanup: true
  email: code+tuyapinpm@maxisom.me
  api_key:
    secure: gkcDi8oIIH4lz1XK0IdVTk1vZtsHm+rYAxgL8iF2Asfz9LY/7knnA1pqBfxkqHExZolpm0monIl6TCwWuuf03y5fnQi12aRDXy51jNSbNrgiJXsy72BR5K8msMlW+p/3CyAQCqw4JpG7q8sQqfDgw2A1DtouZyN4i9EqUyg4O2ET3NPELfEpThiEs66dFUGbvDGulXvY6PtIs2naQIXs4CHHIpI3KlaFKBwV3+me2MZSEO+OaU2U12r2ixp4zpWITMT52S/+t09zoUDsHuFMKxVgFNaDodT4hAL5NSIlnb9RzuzgAL7zJjKWuum2UvcC9s392Va2ec7t5shpL2+6I+0zVjSi00Izl8NecKOyv3Vq9KmWsZvnCiqPDi5L/pNTExO7XW6c2pE1p50cXYWQD2To8oEq5CjYr7zfQk/aO6AdhrZz2VeWxNibbbCV8LiDphTm0dALwzJwkATiYnT+p8Ku0ZZll9y2VfKag6OrrFQEDfzfowG63+/S5LuqFB7MZlaGoPLPNzHniyjaJVJImbR/pQPvdj6SshpNNPvw6iGmbr0GpZmgDegZYVMYXVD4e/7DhtiWaTU2BeLB/CMhm4TJ0vubn5T3V6abSrvIVwY6te/+hQzqwbeNk+K++dA9RewuXma+JioHrqucZ/rodYvzlEoYdrcbqZJLofo+Nhw=
  on:
    tags: true
    repo: TuyaAPI/driver
    branch: master
