language: node_js
node_js:
- stable
script:
- npm run travis
deploy:
  provider: npm
  skip_cleanup: true
  email: code+tuyapinpm@maxisom.me
  api_key:
    secure: oeYM2NFr6pHaSffH3oYiMzKfIpmdCSMPpIEvJ4N/tPgxs5Lp7//e0EDaV5zxcbztBOqTkIWbcWO1F5vrfgkus7CXD/pc0xYFf5ySLU/23fjAhk6QyKVqqANOdrBPXXPdeuvXFHlYpGaIhQJfksr55CkuPTAV/6l4gLvHmwutWA77D2WOtx0GzVcJyeBP82aWhaC7AciOc8CA6Dd4CjemD+MgNIK0nrtxhbR2CylxfSyo5SCCruKh2GTstI9K1jSXDEg6+k6wPaXcYTEWJc7Uk7zJPYLEZsS/7PH1uXG1un/ZjiiC67izWiDogMopiG7cm6YeZ9mwJvFjTuQIYnVpajIZtSp6aoDi8aL00B+WGzJdfKwaJVqWT+2WxXC4Agc7Ew000tgrVob6Gs+vVutifLFNJQwHXaJONk9A7qw6B1J6+HI3TWMUbOsQO/M/l5vqx4Z7MsJ9IOQzt3t49ov7adpGalUErLmFP09artVKKzdkJ/M2/UUaWmEbtFSsktFN5dcTtkXIjOlZKK8McvVPDPXL0idx63vhbwAUWfis9YDoyLtNSl3Pb0GqNI3TBaVzclMH9bfr5SqAL/fWLZzks7G2sZUXi8qI3uv1l1zDjYqvEeJj7oHNn22Rqw13dQf7Y7ppPU3dcaENLPXjJsZQ18FLVqLr8Nl/hQ6UCs1wC3g=
  on:
    tags: true
    repo: TuyaAPI/driver
    branch: master
